function dxout = state_eq(in1,in2)
%STATE_EQ
%    DXOUT = STATE_EQ(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/29 00:14:55

fd = in2(1,:);
tau = in2(2,:);
x_temp1 = in1(1,:);
x_temp2 = in1(2,:);
x_temp4 = in1(4,:);
t2 = cos(x_temp1);
t3 = sin(x_temp1);
t4 = x_temp1.*2.0;
t5 = x_temp2.^2;
t6 = t2.^2;
t7 = sin(t4);
mt1 = [x_temp2;(t3.*-8.2404e+4+tau.*3.5e+4+x_temp2.*5.25e+2-x_temp4.*1.925e+3+fd.*t2.*2.1e+4+t5.*t7.*2.304e+3+t2.*tau.*9.6e+4-t2.*x_temp2.*1.92e+3-t2.*x_temp4.*8.64e+3)./(t6.*4.608e+3-6.72e+3);x_temp4];
mt2 = [((t3.*-4.1202e+5-t7.*1.130112e+6+tau.*4.015e+6-x_temp2.*7.4175e+4-x_temp4.*3.55225e+5+fd.*t2.*1.05e+5+fd.*t6.*5.76e+5+t3.*t5.*1.8432e+5+t5.*t7.*1.152e+4+t2.*tau.*1.44e+6+t2.*x_temp2.*4.8e+3-t2.*x_temp4.*9.6e+4).*(-1.0./2.4e+2))./(t6.*9.6e+1-1.4e+2)];
dxout = [mt1;mt2];
end
