function dxout = state_eq(in1,in2)
%STATE_EQ
%    DXOUT = STATE_EQ(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/07/23 02:35:33

tau = in2(2,:);
x_temp1 = in1(1,:);
x_temp2 = in1(2,:);
x_temp4 = in1(4,:);
et1 = tau.*1.05798088837641e+4;
et2 = x_temp1.*(-3.047029079740581e+2);
mt1 = [x_temp2];
mt2 = [tau.*(-2.772312888581236e+3)+x_temp1.*1.319071033322576e+2];
mt3 = [x_temp4;et1+et2];
dxout = [mt1;mt2;mt3];
end
