function dxout = state_eq(in1,in2)
%STATE_EQ
%    DXOUT = STATE_EQ(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024/02/21 00:28:37

force1 = in2(1,:);
force2 = in2(2,:);
x_temp1 = in1(1,:);
x_temp2 = in1(2,:);
x_temp4 = in1(4,:);
t2 = cos(x_temp1);
t3 = sin(x_temp1);
t4 = x_temp1.*2.0;
t5 = x_temp2.^2;
t6 = sin(t4);
mt1 = [x_temp2;((force1.*2.144e+5-force2.*2.144e+5+t3.*5.25816e+5-x_temp2.*5.1456e+4+x_temp4.*2.144e+4-force2.*t2.*1.5e+4+t2.*x_temp4.*1.5e+3-t2.*t3.*t5.*1.125e+3).*(-1.0./5.0))./(t2.^2.*2.25e+2-9.648e+3);x_temp4];
mt2 = [(force1.*4.288e+5-force2.*5.188e+5+t3.*1.051632e+6+t6.*3.67875e+4-x_temp2.*1.02912e+5+x_temp4.*5.188e+4+force1.*t2.*3.0e+4-force2.*t2.*6.0e+4-t3.*t5.*6.75e+3-t5.*t6.*1.125e+3-t2.*x_temp2.*7.2e+3+t2.*x_temp4.*6.0e+3)./(cos(t4).*1.125e+3-9.5355e+4)];
dxout = [mt1;mt2];
end
